[package]
name = "asset-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
serde = { workspace = true }
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"

