[package]
name = "graphics3d"
version = "0.1.0"
edition = "2021"

[dependencies]
ecs = { path = "../ecs" }
game = { path = "../game" }
asset = { path = "../asset" }
spatial = { path = "../spatial" }
graphics = { path = "../graphics" }
crc32fast = { workspace = true }
serde = { workspace = true }
